#pragma once

#define POINTING_DEVICE_INVERT_Y
#define SPI_SCK_PIN GP18
#define SPI_MOSI_PIN GP19
#define SPI_MISO_PIN GP20
#define PMW33XX_CS_PIN GP21 // SPI CS pin.

#define PMW33XX_CPI 800
#define PMW33XX_CLOCK_SPEED 2000000 
#define MOUSE_EXTENDED_REPORT 
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
